# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: inspection-site.eao-evidence-locker
  version: '1.0.2'
  description: The core site credential issued by EAO Evidence Locker
  endpoint: $ENDPOINT_URL
  path: /eao-evidence-locker/inspection-site
  # identify the attribute which identify the owning organization
  topic: project_id
  attributes:
    project_id:
      description: Project ID issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: helper_uuid
      required: true
    project_name:
      description: Project name issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    location:
      description: Location issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    entity_type:
      description: Project Type
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    entity_status:
      description: Project Status
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    effective_date:
      label_en: Credential Effective Date
      description_en: Date Credential is effective
      required: true
    registration_date:
      label_en: Project Start Date
      description_en: Date the Project (Site) started
      required: true

- name: safety-inspection.eao-evidence-locker
  version: '1.0.2'
  description: The safety-inspection credential issued by EAO Evidence Locker
  endpoint: $ENDPOINT_URL
  path: /eao-evidence-locker/safety-inspection
  # identify the attribute which identify the owning organization
  topic: project_id
  # optionally identify additional attributes to uniquely identify a credential
  cardinality: inspection_id
  # optionally identify a dependant proof request
  proof_request: registration
  attributes:
    project_id:
      description: Project ID issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    inspection_id:
      description: ID issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    inspector_name:
      description: The name of the inspector
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    inspector_email:
      description: The public email addres for the inspector
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    created_date:
      description: Date inspection was created
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    updated_date:
      description: Date inspection was last updated
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    hash_value:
      description: Hash value of inspection report as uploaded
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    effective_date:
      label_en: Credential Effective Date
      description_en: Date Credential is effective
      required: true

- name: inspection-document.eao-evidence-locker
  version: '1.0.2'
  description: A document credential attached to an inspection issued by EAO Evidence Locker
  endpoint: $ENDPOINT_URL
  path: /eao-evidence-locker/inspection-document
  # identify the attribute which identify the owning organization
  topic: project_id
  # optionally identify additional attributes to uniquely identify a credential
  cardinality: 
    - project_id
    - inspection_id
    - document_id
    # optionally identify a dependant proof request
  proof_request: inspection
  attributes:
    project_id:
      description: Project ID issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    inspection_id:
      description: Inspection ID issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    document_id:
      description: Observation ID issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    requirement:
      description: The requirement to satisfy the observation and return to compliance
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    has_media:
      description: The number of media (Audio, Photo, Video) attached to the observation
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    coordinates:
      description: The geographic coordinates (latitude, longitude) at which the observation was made
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: false
    created_date:
      description: Date document was created
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    updated_date:
      description: Date document was last updated
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    hash_value:
      description: Hash value of document as uploaded
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    effective_date:
      label_en: Credential Effective Date
      description_en: Date Credential is effective
      required: true

### eof ###

