# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  eao-evidence-locker:
    name: EAO Evidence Locker
    abbreviation: eao-evidence-locker
    url: https://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/environmental-assessments
    email: eaoinfo@gov.bc.ca
    logo_path: ../assets/img/eao-evidence-locker-logo.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-evlockr_issuer}
      seed: $WALLET_SEED_VONX
      type: $WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
    - description: The core site credential issued by EAO Evidence Locker
      schema: inspection-site.eao-evidence-locker
      issuer_url: $ENDPOINT_URL/eao-evidence-locker/inspection-site
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        source_id:
          input: project_id
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: name
        fields:
          text:
            input: project_name
            from: claim
          type:
            input: project_name
            from: value
      - model: attribute
        fields:
          type:
            input: location
            from: value
          value:
            input: location
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status
            from: value
          format:
            input: category
            from: value
          value:
            input: entity_status
            from: claim

    - description: The safety-inspection credential issued by EAO Evidence Locker
      schema: safety-inspection.eao-evidence-locker
      issuer_url: $ENDPOINT_URL/eao-evidence-locker/safety-inspection
      depends_on:
      - registration
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        source_id:
          input: project_id
          from: claim
        type:
          input: registration
          from: value
      cardinality_fields:
      - project_id
      - inspection_id
      mapping:
      - model: attribute
        fields:
          type:
            input: updated_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: updated_date
            from: claim
      - model: attribute
        fields:
          type:
            input: team_id
            from: value
          value:
            input: team_id
            from: claim
      - model: attribute
        fields:
          type:
            input: project_id
            from: value
          value:
            input: project_id
            from: claim
      - model: attribute
        fields:
          type:
            input: inspection_id
            from: value
          value:
            input: inspection_id
            from: claim
      - model: attribute
        fields:
          type:
            input: created_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: created_date
            from: claim
      - model: attribute
        fields:
          type:
            input: hash_value
            from: value
          value:
            input: hash_value
            from: claim

    - description: A document credential attached to an inspection issued by EAO Evidence
        Locker
      schema: inspection-document.eao-evidence-locker
      issuer_url: $ENDPOINT_URL/eao-evidence-locker/inspection-document
      depends_on:
      - inspection
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        source_id:
          input: project_id
          from: claim
        type:
          input: registration
          from: value
      cardinality_fields:
      - project_id
      - inspection_id
      - document_id
      mapping:
      - model: attribute
        fields:
          type:
            input: updated_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: updated_date
            from: claim
      - model: attribute
        fields:
          type:
            input: project_id
            from: value
          value:
            input: project_id
            from: claim
      - model: attribute
        fields:
          type:
            input: inspection_id
            from: value
          value:
            input: inspection_id
            from: claim
      - model: attribute
        fields:
          type:
            input: created_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: created_date
            from: claim
      - model: attribute
        fields:
          type:
            input: document_type
            from: value
          value:
            input: document_type
            from: claim
      - model: attribute
        fields:
          type:
            input: hash_value
            from: value
          value:
            input: hash_value
            from: claim
      - model: attribute
        fields:
          type:
            input: document_id
            from: value
          value:
            input: document_id
            from: claim

verifiers:
  bctob:
    name: BC OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
    wallet:
      seed: "tob-verifier-wallet-000000000001"

proof_requests:
  registration:
    version: '1.0.1'
    schemas:
      - key:
          did: Mrho166NhN7ArUqRL8t1sR
          name: inspection-site.eao-evidence-locker
          version: '1.0.1'
        attributes:
          - project_id

  inspection:
    version: '1.0.1'
    schemas:
      - key:
          did: Mrho166NhN7ArUqRL8t1sR
          name: safety-inspection.eao-evidence-locker
          version: '1.0.1'
        attributes:
          - project_id
          - inspection_id


### eof ###
